language: python
os: linux
notifications:
  email: false
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      os: linux
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      addons:
        apt:
          packages:
          - x11-utils
          - libxkbcommon-x11-0
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      addons:
        homebrew:
          packages:
          - create-dmg
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 freeze
script:
  - python3 pack.py || python pack.py

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mv "dist/kflash_gui.tar.xz" "dist/kflash_gui_${TRAVIS_TAG}_linux.tar.xz" ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mv "dist/kflash_gui.dmg" "dist/kflash_gui_${TRAVIS_TAG}_macOS.dmg" ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then mv "dist/kflash_gui.7z" "dist/kflash_gui_${TRAVIS_TAG}_windows.7z" ; fi

deploy:
  provider: releases
  overwrite: true
  token:
    secure: "f/cXevhUkauQ4Q0QlbvwLWrmh+fxxrkwsCRdaJw3zKmlsOoj4TAcajJNy3Y5tJ3wFLOoL8ZS2XcZKY165cLUSP17v2iuGFuDgWUoJR9bRHi3mTEiU21VtoHLIUmWRJJLbY8sO2OtIKvUbWeniT29b4/UDQrfC7Ng4+2pXI/eZ2SPOm+kqvjLtLVrGINBpnVo45e4pCQO/BCfxH3vbRMQAjFkXpOxO10pCD4+E0HSifE1LSMymoDYDQozg8TomEoZq3bSLww5Mod8q0Q+Z0LnpfLqepHpTwpW4SqKnQi2RKDzVrTI8zbPyA62zO4f5s1/z+cshOGusLHpI1isNJQnyDR6HmzjaukCHc/cv5M0VYd5GbBddR9dzF6DrAs1LjOVuCR9ZgXmJ5jQaV2xpaYVyLcIJsNelpIgUu3Ob6RRKR5T2WZgKZEu8kgWpAdKqvUVS+WDabKJWjxmWxar0GlkuIOKRW7mkMowE/P0Dtzw07UpfIFI6dFlv7cp3tQad9LN+tMs4ie+JflWbovz6a7RV5JOK8v8HRqawL3UmwLx7WNFTZiQnaXcFOCvtsZ3jmZUb00Q16vzUevyPxoBziG50BddMM41K6zSdIX8V+oUeYQwwRblS0GBgDbwKVK20kKWETWWzaqmG5LJndfYppPbuZOflRGh3GJE7KblRHefSAc="
  file_glob: true
  file:
    - "./dist/*.dmg"
    - "./dist/*.tar.xz"
    - "./dist/*.7z"
  cleanup: false
  prerelease: true
  on:
    tags: true
