notifications:
  email: false
language: python
jobs:
  include:
    - os: osx
      python: 3.8
    - os: linux
      python: 3.8
      addons:
        apt:
          packages:
          - x11-utils
          - libxkbcommon-x11-0
      services: xvfb
install:
  - python --version
  - pip install -e .
  - pip freeze
script:
  - python pack.py
deploy:
  provider: releases
  overwrite: true
  token:
    secure: $SECURE_API_KEY
  file_glob: true
  file:
    - "dist_app/*.dmg"
  skip_cleanup: true
  on:
    branch: master
    tags: true
